-- Keep the canonical 50-creative library aligned with the landing catalog.
-- IDs are stable because creative_references points to this table.
insert into public.creative_templates (
  id,
  name,
  category,
  awareness_level,
  purpose,
  usage_hint,
  is_active
)
values
  (1, 'Tweet', 'social', 'N3', 'Un tweet elogiando tu producto, con avatar, likes y retweets. El cerebro lo lee como opinión de un tercero, no como publicidad — por eso baja la guardia antes de que te des cuenta de que es un anuncio.', 'Es el creativo con mejor CTR en frío del pack. Si vas a probar uno solo, probá este.', true),
  (2, 'Reseña 5 estrellas', 'social', 'N4', 'Una reseña real ampliada a pantalla completa: estrellas, nombre, verificado y la frase que más pega. Convierte una review escondida en tu web en el argumento central del anuncio.', 'Retargeting a gente que vio el producto y no compró. La duda que tienen es "¿funcionará?" y esto la responde.', true),
  (3, 'Muro de reseñas', 'social', 'N4', 'Grid de 6 a 9 reseñas juntas. No convence una — convence el volumen. El mensaje real es "todo el mundo ya lo compró menos vos".', 'Cuando ya tenés más de 50 reseñas. Con pocas se nota y juega en contra.', true),
  (4, 'Captura de WhatsApp', 'social', 'N3', 'Conversación real con un cliente feliz, con los tildes azules. Es el formato más creíble que existe porque es el que todos usamos todos los días.', 'Ideal para servicios, high ticket y productos donde hay conversación previa a la venta.', true),
  (5, 'Comentario destacado', 'social', 'N3', 'Un comentario de Instagram o TikTok ampliado, con los likes visibles. Funciona porque el usuario está viendo el anuncio en la misma app donde vive ese comentario.', 'Perfecto si tenés contenido orgánico con comentarios buenos. Reciclás lo que ya tenés gratis.', true),
  (6, 'Antes y después', 'social', 'N2', 'Split vertical u horizontal. El creativo más viejo del mundo y sigue siendo de los que más venden porque muestra la transformación sin explicarla.', 'Skincare, fitness, reformas, limpieza, estética. Cualquier cosa con resultado visible.', true),
  (7, 'Testimonial con rostro', 'social', 'N4', 'Foto real del cliente + frase textual + nombre. La cara humana es lo que frena el scroll; la frase es lo que cierra.', 'Cuando el cliente te dio permiso y tiene una historia concreta. Nunca con foto de banco de imágenes: se nota.', true),
  (8, 'DM "¿queda stock?"', 'social', 'N5', 'Captura de un mensaje directo preguntando si todavía hay unidades. Comunica demanda y escasez al mismo tiempo, sin que vos digas ninguna de las dos cosas.', 'Retargeting caliente y remarketing de carrito abandonado.', true),
  (9, 'Contador social', 'social', 'N3', 'Un número gigante: "12.483 personas ya lo están usando". La cifra hace todo el trabajo. Cero adorno.', 'Cuando el número ya es respetable. Debajo de 1.000 clientes, mejor no.', true),
  (10, 'Como se vio en', 'social', 'N2', 'Logos de medios, podcasts o marcas donde apareciste. Autoridad prestada: te asocia a marcas que el usuario ya respeta.', 'Público frío que no te conoce. Es un atajo de confianza.', true),
  (11, 'Review de marketplace', 'social', 'N4', 'Captura de una reseña de Mercado Libre o Amazon, con el sello de compra verificada. El "compra verificada" vale más que cualquier adjetivo que escribas.', 'Si vendés también en marketplaces. Trae la credibilidad de la plataforma a tu tienda propia.', true),
  (12, 'UGC con producto en mano', 'social', 'N3', 'Foto tipo celular, mala luz a propósito, producto en mano + frase escrita encima. Se ve como contenido, no como anuncio, y eso es exactamente el punto.', 'Feed y Stories en frío. Es el que menos "cara de ad" tiene de los 50.', true),
  (13, 'Precio tachado', 'oferta', 'N5', 'Precio viejo tachado, precio nuevo enorme. El ancla de precio es el sesgo más viejo y más rentable del marketing.', 'Cierre de venta. Retargeting de 7 días, gente que ya vio el producto.', true),
  (14, 'Bundle / Kit', 'oferta', 'N5', 'Grid con todos los productos del combo y un precio único abajo. Sube el ticket promedio sin que el cliente sienta que gastó más.', 'Cuando querés levantar el AOV. Es el creativo que más plata suele mover por venta.', true),
  (15, 'Fecha límite', 'oferta', 'N5', 'Un contador o una fecha concreta en pantalla. La urgencia real convierte; la falsa te quema la marca. Poné una fecha que se cumpla de verdad.', 'Últimas 48-72hs de una promo. No lo dejes corriendo siempre o pierde todo el efecto.', true),
  (16, 'Regalo con la compra', 'oferta', 'N5', 'El producto principal más el regalo destacado con un lazo o un badge. Regalar algo funciona mejor que descontar lo mismo en plata: no devalúa tu producto.', 'Cuando no querés bajar el precio pero necesitás empujar la conversión.', true),
  (17, '2x1 / 3x2', 'oferta', 'N5', 'Cantidad visual. Se entiende en medio segundo sin leer una palabra.', 'Productos de consumo repetido: cosmética, suplementos, comida, descartables.', true),
  (18, 'Envío gratis', 'oferta', 'N4', 'El envío es la razón número uno de carrito abandonado. Si es gratis, no lo escondas en el checkout: gritalo en el creativo.', 'Retargeting de carrito abandonado. Es el que más recupera de todos.', true),
  (19, 'Cupón visual', 'oferta', 'N5', 'El código de descuento gigante en pantalla. El usuario lo memoriza y llega al checkout con la decisión medio tomada.', 'Campañas de temporada: Hot Sale, Black Friday, Navidad.', true),
  (20, 'Escalera de precio', 'oferta', 'N5', 'Tabla mostrando que cuanto más llevás, menos pagás por unidad. Empuja al pack grande solo con lógica, sin presión.', 'Suplementos, cosmética, cualquier producto con reposición mensual.', true),
  (21, 'Sello de garantía', 'oferta', 'N4', 'La garantía como protagonista, no como letra chica. Te saca el riesgo de encima del cliente y lo pone sobre vos — que es donde tiene que estar.', 'Productos caros o marcas nuevas donde la desconfianza es el freno principal.', true),
  (22, 'Cuotas sin interés', 'oferta', 'N5', 'El precio partido en cuotas, con la cuota más grande que el total. Cambia la percepción de "caro" a "accesible" sin tocar el precio.', 'Ticket alto. Indispensable en Argentina y en LATAM en general.', true),
  (23, 'Nosotros vs Ellos', 'vs', 'N4', 'Tabla de dos columnas con tildes verdes de tu lado y cruces rojas del otro. Polariza, y polarizar vende.', 'Mercados saturados donde el cliente ya está comparando opciones.', true),
  (24, 'Lado a lado', 'vs', 'N4', 'Tu producto y la alternativa, foto contra foto, con las diferencias señaladas. Deja que la imagen argumente sola.', 'Cuando tu producto gana visualmente. Si no gana a simple vista, no uses este.', true),
  (25, 'Comparación de costo', 'vs', 'N3', 'Tu precio contra lo que gasta el cliente hoy en la alternativa cara. Reencuadra tu producto como ahorro, no como gasto.', 'Servicios, software, y todo lo que reemplaza algo más caro.', true),
  (26, 'Pagás X, recibís Y', 'vs', 'N4', 'Un lado el precio, del otro la pila de todo lo que incluye. Desbalancea la ecuación de valor a tu favor.', 'Bundles, cursos, membresías, kits. Todo lo que tiene muchos componentes.', true),
  (27, 'Checklist de compra', 'vs', 'N3', '"Qué mirar antes de comprar" con 5 criterios que — casualmente — solo vos cumplís todos. Educás y descalificás a la competencia en el mismo movimiento.', 'Público que está investigando y todavía no eligió marca.', true),
  (28, 'Composición comparada', 'vs', 'N3', 'Tus ingredientes o materiales contra los del genérico. Funciona porque es verificable y el cliente puede chequearlo.', 'Suplementos, skincare, alimentos, textiles. Todo donde la fórmula importa.', true),
  (29, 'Con vs sin', 'vs', 'N2', 'La línea de tiempo del cliente con tu producto y sin él. Vende el futuro, no el objeto.', 'Productos de transformación lenta donde el resultado tarda en verse.', true),
  (30, 'Listicle', 'educativo', 'N1', '"Los 5 errores que están arruinando tu X". Entrega valor antes de pedir nada. Es la puerta de entrada al mundo del que no te conoce.', 'Top of funnel puro. El mejor creativo para llenar públicos de retargeting barato.', true),
  (31, 'Estadística brutal', 'educativo', 'N1', 'Un número enorme que incomoda: "el 73% de las mujeres tiene esto y no lo sabe". El dato frena el scroll mejor que cualquier foto.', 'Frío absoluto. Especialmente si el problema todavía no es consciente.', true),
  (32, 'Mito vs realidad', 'educativo', 'N2', 'Contradecís una creencia común. La contradicción genera curiosidad y la curiosidad genera clicks.', 'Nichos con mucha desinformación: salud, finanzas, nutrición, marketing.', true),
  (33, 'Diagrama señalado', 'educativo', 'N2', 'Flechas y etiquetas sobre una imagen explicando qué pasa y por qué. Enseña algo, y quien te enseña algo se gana tu confianza.', 'Productos técnicos que necesitan una explicación para que se entienda el valor.', true),
  (34, 'Pregunta directa', 'educativo', 'N2', '"¿Te levantás cansado aunque duermas 8 horas?" Si la respuesta es sí, ya te ganaste al lector. El resto del anuncio es un trámite.', 'Cuando conocés muy bien el dolor exacto de tu cliente. Si la pregunta es genérica, no funciona.', true),
  (35, 'Meme', 'educativo', 'N1', 'Humor que el cliente siente propio. Se comparte, y un anuncio compartido es alcance gratis.', 'Marcas jóvenes con tono suelto. Con una marca seria queda forzado y se nota.', true),
  (36, 'Comic', 'educativo', 'N1', 'Dos a cuatro viñetas: problema, intento fallido, tu producto, resolución. Cuenta una historia entera en una sola imagen.', 'Frío. Es de los pocos estáticos que retienen la atención como si fuera un video.', true),
  (37, 'Sí / No', 'educativo', 'N2', 'Dos columnas con lo que hay que hacer y lo que no. Simple, escaneable, y el cliente se autoevalúa mientras lo lee.', 'Educar rápido a un público que recién empieza a entender su problema.', true),
  (38, 'Definición', 'educativo', 'N1', 'Formato entrada de diccionario definiendo el problema con nombre y todo. Ponerle nombre a lo que sentís es la mitad de la solución.', 'Cuando el cliente tiene el síntoma pero no sabe cómo se llama.', true),
  (39, 'Nota manuscrita', 'educativo', 'N2', 'Texto escrito a mano sobre papel. Rompe el patrón visual del feed entero: en un scroll de imágenes limpias, la letra manuscrita grita.', 'Cuando querés un mensaje personal y cercano. Excelente para marcas de fundador.', true),
  (40, 'Hero limpio', 'demo', 'N4', 'El producto solo, fondo plano, luz perfecta. Aburrido y necesario: es el que sostiene el escalado cuando los creativos raros se queman.', 'Retargeting y catálogo. Es el caballo de tiro, no el ganador de la carrera.', true),
  (41, 'Features señaladas', 'demo', 'N3', 'El producto con líneas y etiquetas apuntando a cada beneficio. Convierte características en razones para comprar.', 'Productos con varios diferenciales que se pierden si solo mostrás la foto.', true),
  (42, 'Lifestyle en uso', 'demo', 'N3', 'El producto usado por una persona real en contexto real. El cliente se proyecta: no ve el producto, se ve a sí mismo.', 'Moda, deco, tecnología, todo lo aspiracional.', true),
  (43, 'Despiece', 'demo', 'N3', 'El producto abierto o explotado, mostrando cada capa o componente. Comunica calidad e ingeniería sin decir "somos de calidad".', 'Productos donde el interior justifica el precio.', true),
  (44, 'Escala real', 'demo', 'N3', 'Tu producto al lado de un objeto conocido: una mano, una moneda, un teléfono. Elimina la duda de tamaño, que es una objeción silenciosa que mata muchas ventas.', 'Cualquier producto físico chico. Es de los más subestimados del pack.', true),
  (45, 'Paso a paso 1-2-3', 'demo', 'N4', 'Tres cuadros mostrando lo simple que es usarlo. Mata la objeción de "esto va a ser complicado" antes de que aparezca.', 'Productos que parecen difíciles de usar aunque no lo sean.', true),
  (46, 'Qué viene en la caja', 'demo', 'N4', 'Todo el contenido desplegado y ordenado, tipo flat lay. Justifica el precio mostrando cantidad.', 'Kits, combos, cajas de suscripción, cualquier cosa con varios componentes.', true),
  (47, 'Secuencia de 3 frames', 'demo', 'N3', 'Tres momentos del producto funcionando, uno al lado del otro. Es lo más cerca que un estático puede estar de un video, al costo de un estático.', 'Cuando el video rinde pero no tenés presupuesto para producirlo.', true),
  (48, 'Aval de experto', 'autoridad', 'N3', 'Un profesional con credencial respaldando el producto. Toma prestada la confianza que a tu marca todavía le falta.', 'Salud, estética, suplementos, finanzas. Cualquier rubro donde el riesgo percibido es alto.', true),
  (49, 'Sellos y certificaciones', 'autoridad', 'N4', 'Certificados, aprobaciones y sellos como protagonistas. Cierra las objeciones de seguridad de un plumazo.', 'Productos regulados o mercados donde ya hubo estafas y la gente desconfía.', true),
  (50, 'Carta del fundador', 'autoridad', 'N2', 'Tu foto y tu historia: por qué existe esto. La gente no le compra a las empresas, le compra a las personas.', 'Marcas nuevas sin reseñas todavía. Es lo único que tenés cuando no tenés prueba social.', true)
on conflict (id) do update
set
  name = excluded.name,
  category = excluded.category,
  awareness_level = excluded.awareness_level,
  purpose = excluded.purpose,
  usage_hint = excluded.usage_hint,
  is_active = excluded.is_active;
